/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: 'lf',
  tabWidth: 2,
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  printWidth: 80,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  jsxSingleQuote: true,
  semi: true,
  useTabs: false,
  arrowParens: 'always',
  htmlWhitespaceSensitivity: 'css',
};
